
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: <YOUR_ACR_NAME>.azurecr.io/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_URI
          value: mongodb://mongo:27017/tasksdb
        - name: KAFKA_BOOTSTRAP
          value: kafka:9092
        - name: MINIO_ENDPOINT
          value: minio:9000
        - name: MINIO_ACCESS_KEY
          value: minioadmin
        - name: MINIO_SECRET_KEY
          value: minioadmin
        - name: MINIO_BUCKET
          value: uploads
